#!/system/bin/sh
# 02setuphuawei for BCM4319
# by Alberto96
#
# This script will set up the proper MAC addresses

echo "02setuphuawei"
echo "---------------"

## MAC addresses

# MAC address present in stock U8150 nv_4319.txt
originalmac="00:90:4c:14:43:19"

# Set a custom serial if specified by the user
if [ "$(getprop persist.sys.usbserial)" != "" ]; then
    customusbserial=$(getprop persist.sys.usbserial)
    echo "USB serial (user set)                 : $customusbserial"
    echo $customusbserial > /sys/module/g_android/parameters/serial_number
fi

# grab the usb serial in lower case format
usbserial=$(cat /sys/module/g_android/parameters/serial_number | tr '[A-Z]' '[a-z]')

# convert to mac address block format
usbmac=$(echo $usbserial | busybox sed 's!^M$!!;s!\-!!g;s!\.!!g;s!\(..\)!\1:!g;s!:$!!')
# get first 5 mac address blocks
firstpart=$(echo $usbmac | cut -d ":" -f 1,2,3,4,5)":"
# get final mac address block
lastpart=$(echo $usbmac | cut -d ":" -f 6)

# calculate wifi final mac block (lastpart + 1)
wifipart=$(printf '%x\n' $((0x$lastpart + 1)))
if [ $(expr length "$wifipart") -eq 3 ]; then
    wifipart=$(printf '%x\n' $((0x$wifipart - 0xFF)))
fi
if [ $(expr length "$wifipart") -eq 1 ]; then
    wifipart=0$wifipart
fi

# calculate bt final mac block (lastpart + 2)
btpart=$(printf '%x\n' $((0x$lastpart + 2)))
if [ $(expr length "$btpart") -eq 3 ]; then
    btpart=$(printf '%x\n' $((0x$btpart - 0xFF)))
fi
if [ $(expr length "$btpart") -eq 1 ]; then
    btpart=0$btpart
fi

# put the parts together
wifimac=$firstpart$wifipart
btmac=$firstpart$btpart

# echo results
echo "USB serial address (real)             : $usbmac"
echo "New WiFi MAC address                  : $wifimac"
echo "New Bluetooth MAC address             : $btmac"

# write the addresses to the appropriate configuration files
cat /system/etc/nv_4319.txt | busybox sed -e s/$originalmac/$wifimac/g >/data/misc/wifi/nv_4319.txt
echo $btmac >/data/misc/bluetooth/bdaddr

exit
